name: QA Automation Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  api-tests:
    name: API Tests - Swagger Petstore
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run API tests
        run: pytest tests/api/ -v --html=reports/api-report.html --self-contained-html

      - name: Upload API report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: api-test-report
          path: reports/api-report.html

  web-tests:
    name: Web Tests - SauceDemo E2E
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Web tests
        run: pytest tests/web/ -v --html=reports/web-report.html --self-contained-html

      - name: Upload Web report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: web-test-report
          path: reports/web-report.html